/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {

    Lab9 lab9 = new Lab9();

    int[] testArr = {2, 42, 56, 78, 78, 45, 57, 34, 77, 2};

    int res = lab9.linearSearch(testArr, 2);
    int res2 = lab9.findIndexLargest(testArr, false);
    int res3 = lab9.findIndexSmallest(testArr, true);
    int rest = lab9.findSmallest(testArr);
    System.out.println("num: " + rest);

    int[][] testArr2 = {{1, 2}, {3, 4}};

    int[][] temp = lab9.bushDensity(testArr2);

    for (int i = 0; i < temp.length; i++) {
      for (int j = 0; j < temp[0].length; j++) {
        System.out.println("sum: " + temp[i][j] + "pos: " + i + ", " + j);
      }
    }
  }
}
