/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {

  private Lab9 lab9 = new Lab9();
  private int[] testArr = {2, 42, 56, 78, 78, 45, 57, 34, 77, 2};

  @Test
  public void whichNumberIsSmallesIndextInTheArray() {

    int result = lab9.findIndexSmallest(testArr, true);
    int result2 = lab9.findIndexSmallest(testArr, false);
    assertEquals((int) result, 0);
    assertEquals((int) result2, 9);
  }

  @Test
  public void whichNumberIsSmallestInArray() {

    int result = lab9.findSmallest(testArr);
    assertEquals(2, result);
  }

  @Test
  public void printLastNameOnStudentsWithPassOrHigher() {

    Person[] students = {
      new Person("pelle", "plutt", 1, 40, "VG"),
      new Person("Jajaja", "ok", 2, 20, "G"),
      new Person("Skalman", "Bamse", 3, 10, "U"),
    };
    String result = lab9.printInformation(students);
    assertEquals("Students with grade pass or above: ", "Last name: plutt, points: 40", result);
  }
}
